Report failing tests

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,4 @@
-name: CI
+name: Continuous Testing
 
 on:
   push:
@@ -26,4 +26,21 @@ jobs:
       - name: Execute `eleet_camel`
         run: opam exec -- dune exec eleet_camel
       - name: Check for diffs in the `tests` directory
-        run: git diff tests
+        run: |
+          failing_tests=()
+          for file in $(git diff --name-only tests)
+          do
+            failing_tests+=$(echo $file | cut -d'/' -f2)
+          done
+          if [ ${#failing_tests[@]} -ne 0 ]
+          then
+            echo -n "Failing tests:"
+            for test in "${failing_tests[@]}"
+            do
+              echo -n " $test"
+            done
+            echo
+            exit 1
+          fi
+          echo "All tests passing"
+
